version: '3'

networks:
  geolocation-distances:

services:
  nginx:
    image: nginx:latest
    container_name: nginx-server
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8060:80"
    depends_on:
      - php
    networks:
      - geolocation-distances

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-app
    volumes:
      - ./src:/var/www
      - ./entrypoint.sh:/entrypoint.sh
    ports:
      - "9000:9000"
    networks:
      - geolocation-distances